---
name: Publish
on:
  push:
    branches:
    - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Image
      run: docker build --tag image .
    - name: Publish Image (GHCR)
      run: |
        GHCR_IMAGE_ID=ghcr.io/hreeder/discord-post-updater

        echo "${{ secrets.GHCR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
        docker tag image $GHCR_IMAGE_ID:latest
        docker push $GHCR_IMAGE_ID
